application: soppmiddag
version: 5
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: lxml
  version: "2.3.5"

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
  secure: always
- url: /call
  script: call.application
  secure: always
- url: /sms
  script: sms.application
  secure: always
- url: /plaintext
  script: plaintext.application
  secure: always
- url: /.*
  static_files: static/info.html
  upload: static/info\.html
  secure: always
